server:
  port: 80

spring:
  application:
    name: api-gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      default-filters:
  #   http://localhost/auth/dologin -> burada segment Path ile yakalanan kisimdir. Yani: "auth/dologin" dir.
  #   burada islenen kisim su sekilde oluyor, segment yeni url duzeninin sonuna ekleniyor. Yani: "/api/v1/auth/dologin" oluyor.
        - RewritePath= /(?<segment>.*) , /api/v1/$\{segment}
      routes:
        - id: auth-service
          uri: http://localhost:9090
          predicates:
            - Path=/auth/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: auth
                fallbackUri: forward:/fallback/auth
        - id: user-service
          uri: http://localhost:9092
          predicates:
            - Path=/user/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: user
                fallbackUri: forward:/fallback/user
        - id: user-service-message
          uri: http://localhost:9092
          predicates:
            - Path=/message/**
        - id: post-service
          uri: http://localhost:9091
          predicates:
            - Path=/post/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: post
                fallbackUri: forward:/fallback/post
