server:
  port: 9092

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: bilgejava8
    password: bilgeadmin*
  cloud:
    compatibility-verifier:
      enabled: false
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sosyalmedyadb
      username: bilgeadmin
      password: bilge33**